# use Ganache's forked mainnet mode as the default network
networks:
  default: development
  networks:
        # any settings given here will replace the defaults
        development:
            host: http://127.0.0.1
            port: 8545
            gas_price: 0
            persist: false
            reverting_tx_gas_limit: 6721975
            fork: http://127.0.0.1:8545

autofetch_sources: true

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.1.0

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.6.12
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.1.0"

reports:
  exclude_paths:
    - contracts/test/Token.sol
  exclude_contracts:
    - SafeMath
    - SafeERC20
    - Address
